{
 "title": "Onehouse Data Metrics 2.0",
 "description": "Core metrics for monitoring the Onehouse powered lakehouse",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "ohds_deltacommit_totalBytesWritten"
    }
   },
   {
    "name": "table",
    "query": {
     "query": "ohds_deltacommit_totalBytesWritten{database=~\"$database\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Source Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[Kafka Source] Number of messages pending to be ingested",
   "type": "timeseries",
   "description": "The number of messages in Kafka Topic that have not been ingested to Onehouse table yet.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltastreamer_kafkaDelayCount{table=~\"$table\", database=~\"$database\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Number of duplicates across tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "diff_job_duplicate_count{table_name=~\"$table\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Write Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top 10 tables with the most bytes written",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by(table, database) (ohds_deltacommit_totalBytesWritten{table=~\"$table\", database=~\"$database\"})) / ( 1024 * 1024)",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Total bytes written",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (ohds_deltacommit_totalBytesWritten{table=~\"$table\", database=~\"$database\"}) / ( 1024 * 1024)",
     "legendFormat": "total_bytes_written"
    }
   ]
  },
  {
   "title": "Records Written over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltacommit_totalRecordsWritten{table=~\"$table\", database=~\"$database\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Top 10 tables with the most records written",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (table) (ohds_deltacommit_totalRecordsWritten{table=~\"$table\", database=~\"$database\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Upserted Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltacommit_totalUpdateRecordsWritten{table=~\"$table\", database=~\"$database\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Records Inserted Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltacommit_totalInsertRecordsWritten{table=~\"$table\", database=~\"$database\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Total Bytes Written in Ingestion Commits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltacommit_totalBytesWritten{table=~\"$table\", database=~\"$database\"}) / ( 1024 * 1024 * 1024)",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Total Number of Records Deleted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltacommit_totalRecordsDeleted{table=~\"$table\", database=~\"$database\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Total partitions written in Ingestion Commits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltacommit_totalPartitionsWritten{table=~\"$table\", database=~\"$database\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Sync Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync Duration & Configured Sync Frequency",
   "type": "timeseries",
   "description": "We plot the desired sync time for the table vs the actual sync time we could manage based on current compute/memory resources",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltastreamer_syncIntervalSecs{table=~\"$table\", database=~\"$database\"}) / 60",
     "legendFormat": "{{database}}.{{table}}_configured_sync_time"
    },
    {
     "expr": "sum by(table, database) (ohds_deltastreamer_syncDurationSecs{table=~\"$table\", database=~\"$database\"}) / 60",
     "legendFormat": "{{database}}{{table}}_actual_sync_time"
    }
   ]
  },
  {
   "title": "Top 10 Streams with Longest Sync Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "topk(10, sum by(table, database) (ohds_deltastreamer_syncDurationSecs{table=~\"$table\", database=~\"$database\"})) / 60",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Number of consecutive sync lags",
   "type": "timeseries",
   "description": "Plots the number of consecutive syncs where the actual sync duration exceeds the configured sync durations. Note that it is a cumulative sum.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltastreamer_numConsecutiveSyncLags{table=~\"$table\", database=~\"$database\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Absolute time of the last sync",
   "type": "timeseries",
   "description": "Actual local time when the last sync was completed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltastreamer_lastSync{table=~\"$table\", database=~\"$database\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Number of sync failures ",
   "type": "timeseries",
   "description": "Number of sync failures over time. A sync is failed if no data was committed due to some errors. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_deltastreamer_numFailedCommits{table=~\"$table\", database=~\"$database\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Compaction Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Streams with the longest Compaction Durations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "topk(10, sum by(table, database) (ohds_compaction_duration{table=~\"$table\", database=~\"$database\"})) / 60000",
       "legendFormat": "{{database}}.{{table}}"
      }
     ]
    },
    {
     "title": "Time taken by Compaction Commits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum by(table, database) (ohds_compaction_duration{table=~\"$table\", database=~\"$database\"}) / (60 * 1000)",
       "legendFormat": "{{database}}.{{table}}"
      }
     ]
    },
    {
     "title": "Number of bytes compacted by Compaction Commits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum by (table,database) (ohds_compaction_totalBytesWritten{table=~\"$table\", database=~\"$database\"}/(1024*1024))",
       "legendFormat": "{{database}}.{{table}}"
      }
     ]
    },
    {
     "title": "Number of partitions touched by Compaction Commits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "sum by(table, database) (ohds_compaction_totalPartitionsWritten{table=~\"$table\", database=~\"$database\"})",
       "legendFormat": "{{database}}.{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Clustering Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top 10 Streams with the Longest Clustering Durations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "topk(10, sum by(table, database) (ohds_replacecommit_duration{table=~\"$table\", database=~\"$database\"})) / 60000",
       "legendFormat": "{{database}}.{{table}}"
      }
     ]
    },
    {
     "title": "Time taken by Clustering Commits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum by(table, database) (ohds_replacecommit_duration{table=~\"$table\", database=~\"$database\"}) / 60000",
       "legendFormat": "{{database}}.{{table}}"
      }
     ]
    },
    {
     "title": "Total Bytes Written by Clustering Commits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum by(table, database) (ohds_replacecommit_totalBytesWritten{table=~\"$table\", database=~\"$database\"}) / ( 1024 * 1024)",
       "legendFormat": "{{database}}.{{table}}"
      }
     ]
    },
    {
     "title": "Total Partitions Written By Clustering Commits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "sum by(table, database) (ohds_replacecommit_totalPartitionsWritten{table=~\"$table\", database=~\"$database\"})",
       "legendFormat": "{{database}}.{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cleaner Service Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 Streams with the Longest Cleaner Duration",
   "type": "graph",
   "description": "Cleaner service runs periodically to delete all the old versions of files.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(table, database) (ohds_clean_duration{table=~\"$table\", database=~\"$database\"})) / 1000",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Number of Clean Files Deleted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(table, database) (ohds_clean_numFilesDeleted{table=~\"$table\", database=~\"$database\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  }
 ]
}